"""fotos produto e devolucao aluguel

Revision ID: 073776a91a8f
Revises: dbce539e8150
Create Date: 2026-02-04 21:55:13.891700

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '073776a91a8f'
down_revision = 'dbce539e8150'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('foto_path', sa.Text(), nullable=True))
    op.add_column('produtos', sa.Column('foto_mime', sa.String(length=120), nullable=True))
    op.add_column('produtos', sa.Column('foto_nome_original', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'foto_nome_original')
    op.drop_column('produtos', 'foto_mime')
    op.drop_column('produtos', 'foto_path')
    # ### end Alembic commands ###
