"""init

Revision ID: 32371a412bd4
Revises: 
Create Date: 2026-02-03 19:23:25.179313

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32371a412bd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categorias_produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_produto_nome'), 'categorias_produto', ['nome'], unique=False)
    op.create_index(op.f('ix_categorias_produto_parent_id'), 'categorias_produto', ['parent_id'], unique=False)
    op.create_index(op.f('ix_categorias_produto_tipo'), 'categorias_produto', ['tipo'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('documento', sa.String(length=40), nullable=True),
    sa.Column('telefone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_documento'), 'clientes', ['documento'], unique=False)
    op.create_index(op.f('ix_clientes_nome'), 'clientes', ['nome'], unique=False)
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=180), nullable=False),
    sa.Column('documento', sa.String(length=40), nullable=True),
    sa.Column('telefone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fornecedores_documento'), 'fornecedores', ['documento'], unique=False)
    op.create_index(op.f('ix_fornecedores_nome'), 'fornecedores', ['nome'], unique=False)
    op.create_table('locais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=140), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locais_nome'), 'locais', ['nome'], unique=False)
    op.create_index(op.f('ix_locais_tipo'), 'locais', ['tipo'], unique=False)
    op.create_table('marcas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marcas_nome'), 'marcas', ['nome'], unique=True)
    op.create_table('unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unidades_sigla'), 'unidades', ['sigla'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('perfil', sa.String(length=40), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_perfil'), 'usuarios', ['perfil'], unique=False)
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('local_evento', sa.String(length=200), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_cliente_id'), 'eventos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_eventos_data_fim'), 'eventos', ['data_fim'], unique=False)
    op.create_index(op.f('ix_eventos_data_inicio'), 'eventos', ['data_inicio'], unique=False)
    op.create_index(op.f('ix_eventos_nome'), 'eventos', ['nome'], unique=False)
    op.create_index(op.f('ix_eventos_status'), 'eventos', ['status'], unique=False)
    op.create_table('nfe_documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('chave_acesso', sa.String(length=60), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=True),
    sa.Column('serie', sa.String(length=20), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.Column('status_importacao', sa.String(length=20), nullable=False),
    sa.Column('xml_path', sa.String(length=300), nullable=True),
    sa.Column('xml_hash', sa.String(length=80), nullable=True),
    sa.Column('recebida_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nfe_documentos_chave_acesso'), 'nfe_documentos', ['chave_acesso'], unique=True)
    op.create_index(op.f('ix_nfe_documentos_data_emissao'), 'nfe_documentos', ['data_emissao'], unique=False)
    op.create_index(op.f('ix_nfe_documentos_fornecedor_id'), 'nfe_documentos', ['fornecedor_id'], unique=False)
    op.create_index(op.f('ix_nfe_documentos_numero'), 'nfe_documentos', ['numero'], unique=False)
    op.create_index(op.f('ix_nfe_documentos_recebida_em'), 'nfe_documentos', ['recebida_em'], unique=False)
    op.create_index(op.f('ix_nfe_documentos_serie'), 'nfe_documentos', ['serie'], unique=False)
    op.create_index(op.f('ix_nfe_documentos_status_importacao'), 'nfe_documentos', ['status_importacao'], unique=False)
    op.create_index(op.f('ix_nfe_documentos_usuario_id'), 'nfe_documentos', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_nfe_documentos_xml_hash'), 'nfe_documentos', ['xml_hash'], unique=False)
    op.create_table('produtos_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_base', sa.String(length=180), nullable=False),
    sa.Column('categoria_principal_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['categoria_principal_id'], ['categorias_produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_base_categoria_principal_id'), 'produtos_base', ['categoria_principal_id'], unique=False)
    op.create_index(op.f('ix_produtos_base_nome_base'), 'produtos_base', ['nome_base'], unique=False)
    op.create_table('alugueis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.Column('data_saida_prevista', sa.Date(), nullable=False),
    sa.Column('data_devolucao_prevista', sa.Date(), nullable=False),
    sa.Column('data_devolucao_real', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alugueis_cliente_id'), 'alugueis', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_alugueis_data_devolucao_prevista'), 'alugueis', ['data_devolucao_prevista'], unique=False)
    op.create_index(op.f('ix_alugueis_data_devolucao_real'), 'alugueis', ['data_devolucao_real'], unique=False)
    op.create_index(op.f('ix_alugueis_data_saida_prevista'), 'alugueis', ['data_saida_prevista'], unique=False)
    op.create_index(op.f('ix_alugueis_evento_id'), 'alugueis', ['evento_id'], unique=False)
    op.create_index(op.f('ix_alugueis_status'), 'alugueis', ['status'], unique=False)
    op.create_table('compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nfe_documento_id', sa.Integer(), nullable=True),
    sa.Column('numero_documento', sa.String(length=80), nullable=True),
    sa.Column('data_compra', sa.Date(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['nfe_documento_id'], ['nfe_documentos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compras_data_compra'), 'compras', ['data_compra'], unique=False)
    op.create_index(op.f('ix_compras_fornecedor_id'), 'compras', ['fornecedor_id'], unique=False)
    op.create_index(op.f('ix_compras_nfe_documento_id'), 'compras', ['nfe_documento_id'], unique=False)
    op.create_index(op.f('ix_compras_numero_documento'), 'compras', ['numero_documento'], unique=False)
    op.create_index(op.f('ix_compras_status'), 'compras', ['status'], unique=False)
    op.create_index(op.f('ix_compras_usuario_id'), 'compras', ['usuario_id'], unique=False)
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_base_id', sa.Integer(), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.Column('nome_comercial', sa.String(length=220), nullable=False),
    sa.Column('unidade_base_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('eh_alugavel', sa.Boolean(), nullable=False),
    sa.Column('controla_lote', sa.Boolean(), nullable=False),
    sa.Column('controla_validade', sa.Boolean(), nullable=False),
    sa.Column('estoque_minimo', sa.Float(), nullable=True),
    sa.Column('custo_medio', sa.Float(), nullable=True),
    sa.Column('preco_reposicao', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ),
    sa.ForeignKeyConstraint(['produto_base_id'], ['produtos_base.id'], ),
    sa.ForeignKeyConstraint(['unidade_base_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_ativo'), 'produtos', ['ativo'], unique=False)
    op.create_index(op.f('ix_produtos_eh_alugavel'), 'produtos', ['eh_alugavel'], unique=False)
    op.create_index(op.f('ix_produtos_marca_id'), 'produtos', ['marca_id'], unique=False)
    op.create_index(op.f('ix_produtos_nome_comercial'), 'produtos', ['nome_comercial'], unique=False)
    op.create_index(op.f('ix_produtos_produto_base_id'), 'produtos', ['produto_base_id'], unique=False)
    op.create_index(op.f('ix_produtos_sku'), 'produtos', ['sku'], unique=False)
    op.create_index(op.f('ix_produtos_unidade_base_id'), 'produtos', ['unidade_base_id'], unique=False)
    op.create_table('aluguel_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluguel_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_base', sa.Float(), nullable=False),
    sa.Column('quantidade_devolvida_base', sa.Float(), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=True),
    sa.Column('status_item', sa.String(length=20), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aluguel_id'], ['alugueis.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aluguel_itens_aluguel_id'), 'aluguel_itens', ['aluguel_id'], unique=False)
    op.create_index(op.f('ix_aluguel_itens_produto_id'), 'aluguel_itens', ['produto_id'], unique=False)
    op.create_index(op.f('ix_aluguel_itens_status_item'), 'aluguel_itens', ['status_item'], unique=False)
    op.create_table('estoque_saldos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_base', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['local_id'], ['locais.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto_id', 'local_id', name='uq_saldo_produto_local')
    )
    op.create_index(op.f('ix_estoque_saldos_local_id'), 'estoque_saldos', ['local_id'], unique=False)
    op.create_index(op.f('ix_estoque_saldos_produto_id'), 'estoque_saldos', ['produto_id'], unique=False)
    op.create_table('lotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('codigo_lote', sa.String(length=80), nullable=False),
    sa.Column('validade', sa.Date(), nullable=True),
    sa.Column('quantidade_base_atual', sa.Float(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['local_id'], ['locais.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lotes_codigo_lote'), 'lotes', ['codigo_lote'], unique=False)
    op.create_index(op.f('ix_lotes_local_id'), 'lotes', ['local_id'], unique=False)
    op.create_index(op.f('ix_lotes_produto_id'), 'lotes', ['produto_id'], unique=False)
    op.create_index(op.f('ix_lotes_validade'), 'lotes', ['validade'], unique=False)
    op.create_table('produto_embalagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('fator_para_base', sa.Float(), nullable=False),
    sa.Column('permite_fracionar', sa.Boolean(), nullable=False),
    sa.Column('principal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto_id', 'nome', name='uq_produto_embalagem_nome')
    )
    op.create_index(op.f('ix_produto_embalagens_produto_id'), 'produto_embalagens', ['produto_id'], unique=False)
    op.create_index(op.f('ix_produto_embalagens_unidade_id'), 'produto_embalagens', ['unidade_id'], unique=False)
    op.create_table('produtos_categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_produto.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto_id', 'categoria_id', name='uq_produto_categoria')
    )
    op.create_index(op.f('ix_produtos_categorias_categoria_id'), 'produtos_categorias', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_produtos_categorias_produto_id'), 'produtos_categorias', ['produto_id'], unique=False)
    op.create_table('compras_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('embalagem_id', sa.Integer(), nullable=True),
    sa.Column('unidade_informada_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_informada', sa.Float(), nullable=False),
    sa.Column('fator_para_base', sa.Float(), nullable=False),
    sa.Column('quantidade_base', sa.Float(), nullable=False),
    sa.Column('valor_unitario_informado', sa.Float(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('barcode_lido', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['compra_id'], ['compras.id'], ),
    sa.ForeignKeyConstraint(['embalagem_id'], ['produto_embalagens.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['unidade_informada_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compras_itens_barcode_lido'), 'compras_itens', ['barcode_lido'], unique=False)
    op.create_index(op.f('ix_compras_itens_compra_id'), 'compras_itens', ['compra_id'], unique=False)
    op.create_index(op.f('ix_compras_itens_embalagem_id'), 'compras_itens', ['embalagem_id'], unique=False)
    op.create_index(op.f('ix_compras_itens_lote_id'), 'compras_itens', ['lote_id'], unique=False)
    op.create_index(op.f('ix_compras_itens_produto_id'), 'compras_itens', ['produto_id'], unique=False)
    op.create_index(op.f('ix_compras_itens_unidade_informada_id'), 'compras_itens', ['unidade_informada_id'], unique=False)
    op.create_table('movimentacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.Column('aluguel_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('quantidade_informada', sa.Float(), nullable=False),
    sa.Column('unidade_informada_id', sa.Integer(), nullable=False),
    sa.Column('fator_para_base', sa.Float(), nullable=False),
    sa.Column('quantidade_base', sa.Float(), nullable=False),
    sa.Column('custo_unitario', sa.Float(), nullable=True),
    sa.Column('local_origem_id', sa.Integer(), nullable=True),
    sa.Column('local_destino_id', sa.Integer(), nullable=True),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('embalagem_id', sa.Integer(), nullable=True),
    sa.Column('barcode_lido', sa.String(length=64), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('origem', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aluguel_id'], ['alugueis.id'], ),
    sa.ForeignKeyConstraint(['embalagem_id'], ['produto_embalagens.id'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['local_destino_id'], ['locais.id'], ),
    sa.ForeignKeyConstraint(['local_origem_id'], ['locais.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['unidade_informada_id'], ['unidades.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentacoes_aluguel_id'), 'movimentacoes', ['aluguel_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_barcode_lido'), 'movimentacoes', ['barcode_lido'], unique=False)
    op.create_index(op.f('ix_movimentacoes_created_at'), 'movimentacoes', ['created_at'], unique=False)
    op.create_index(op.f('ix_movimentacoes_embalagem_id'), 'movimentacoes', ['embalagem_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_evento_id'), 'movimentacoes', ['evento_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_local_destino_id'), 'movimentacoes', ['local_destino_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_local_origem_id'), 'movimentacoes', ['local_origem_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_lote_id'), 'movimentacoes', ['lote_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_origem'), 'movimentacoes', ['origem'], unique=False)
    op.create_index(op.f('ix_movimentacoes_produto_id'), 'movimentacoes', ['produto_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_tipo'), 'movimentacoes', ['tipo'], unique=False)
    op.create_index(op.f('ix_movimentacoes_unidade_informada_id'), 'movimentacoes', ['unidade_informada_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_usuario_id'), 'movimentacoes', ['usuario_id'], unique=False)
    op.create_table('nfe_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nfe_documento_id', sa.Integer(), nullable=False),
    sa.Column('descricao_xml', sa.String(length=300), nullable=False),
    sa.Column('ean_xml', sa.String(length=64), nullable=True),
    sa.Column('ncm', sa.String(length=20), nullable=True),
    sa.Column('unidade_xml_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_xml', sa.Float(), nullable=False),
    sa.Column('valor_unitario_xml', sa.Float(), nullable=True),
    sa.Column('valor_total_xml', sa.Float(), nullable=True),
    sa.Column('produto_id_sugerido', sa.Integer(), nullable=True),
    sa.Column('embalagem_id_sugerida', sa.Integer(), nullable=True),
    sa.Column('fator_sugerido', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['embalagem_id_sugerida'], ['produto_embalagens.id'], ),
    sa.ForeignKeyConstraint(['nfe_documento_id'], ['nfe_documentos.id'], ),
    sa.ForeignKeyConstraint(['produto_id_sugerido'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['unidade_xml_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nfe_itens_ean_xml'), 'nfe_itens', ['ean_xml'], unique=False)
    op.create_index(op.f('ix_nfe_itens_embalagem_id_sugerida'), 'nfe_itens', ['embalagem_id_sugerida'], unique=False)
    op.create_index(op.f('ix_nfe_itens_ncm'), 'nfe_itens', ['ncm'], unique=False)
    op.create_index(op.f('ix_nfe_itens_nfe_documento_id'), 'nfe_itens', ['nfe_documento_id'], unique=False)
    op.create_index(op.f('ix_nfe_itens_produto_id_sugerido'), 'nfe_itens', ['produto_id_sugerido'], unique=False)
    op.create_index(op.f('ix_nfe_itens_status'), 'nfe_itens', ['status'], unique=False)
    op.create_index(op.f('ix_nfe_itens_unidade_xml_id'), 'nfe_itens', ['unidade_xml_id'], unique=False)
    op.create_table('produto_codigos_barras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('embalagem_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=64), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('principal', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['embalagem_id'], ['produto_embalagens.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='uq_barcode_codigo')
    )
    op.create_index(op.f('ix_produto_codigos_barras_codigo'), 'produto_codigos_barras', ['codigo'], unique=False)
    op.create_index(op.f('ix_produto_codigos_barras_embalagem_id'), 'produto_codigos_barras', ['embalagem_id'], unique=False)
    op.create_index(op.f('ix_produto_codigos_barras_produto_id'), 'produto_codigos_barras', ['produto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produto_codigos_barras_produto_id'), table_name='produto_codigos_barras')
    op.drop_index(op.f('ix_produto_codigos_barras_embalagem_id'), table_name='produto_codigos_barras')
    op.drop_index(op.f('ix_produto_codigos_barras_codigo'), table_name='produto_codigos_barras')
    op.drop_table('produto_codigos_barras')
    op.drop_index(op.f('ix_nfe_itens_unidade_xml_id'), table_name='nfe_itens')
    op.drop_index(op.f('ix_nfe_itens_status'), table_name='nfe_itens')
    op.drop_index(op.f('ix_nfe_itens_produto_id_sugerido'), table_name='nfe_itens')
    op.drop_index(op.f('ix_nfe_itens_nfe_documento_id'), table_name='nfe_itens')
    op.drop_index(op.f('ix_nfe_itens_ncm'), table_name='nfe_itens')
    op.drop_index(op.f('ix_nfe_itens_embalagem_id_sugerida'), table_name='nfe_itens')
    op.drop_index(op.f('ix_nfe_itens_ean_xml'), table_name='nfe_itens')
    op.drop_table('nfe_itens')
    op.drop_index(op.f('ix_movimentacoes_usuario_id'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_unidade_informada_id'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_tipo'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_produto_id'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_origem'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_lote_id'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_local_origem_id'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_local_destino_id'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_evento_id'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_embalagem_id'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_created_at'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_barcode_lido'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_aluguel_id'), table_name='movimentacoes')
    op.drop_table('movimentacoes')
    op.drop_index(op.f('ix_compras_itens_unidade_informada_id'), table_name='compras_itens')
    op.drop_index(op.f('ix_compras_itens_produto_id'), table_name='compras_itens')
    op.drop_index(op.f('ix_compras_itens_lote_id'), table_name='compras_itens')
    op.drop_index(op.f('ix_compras_itens_embalagem_id'), table_name='compras_itens')
    op.drop_index(op.f('ix_compras_itens_compra_id'), table_name='compras_itens')
    op.drop_index(op.f('ix_compras_itens_barcode_lido'), table_name='compras_itens')
    op.drop_table('compras_itens')
    op.drop_index(op.f('ix_produtos_categorias_produto_id'), table_name='produtos_categorias')
    op.drop_index(op.f('ix_produtos_categorias_categoria_id'), table_name='produtos_categorias')
    op.drop_table('produtos_categorias')
    op.drop_index(op.f('ix_produto_embalagens_unidade_id'), table_name='produto_embalagens')
    op.drop_index(op.f('ix_produto_embalagens_produto_id'), table_name='produto_embalagens')
    op.drop_table('produto_embalagens')
    op.drop_index(op.f('ix_lotes_validade'), table_name='lotes')
    op.drop_index(op.f('ix_lotes_produto_id'), table_name='lotes')
    op.drop_index(op.f('ix_lotes_local_id'), table_name='lotes')
    op.drop_index(op.f('ix_lotes_codigo_lote'), table_name='lotes')
    op.drop_table('lotes')
    op.drop_index(op.f('ix_estoque_saldos_produto_id'), table_name='estoque_saldos')
    op.drop_index(op.f('ix_estoque_saldos_local_id'), table_name='estoque_saldos')
    op.drop_table('estoque_saldos')
    op.drop_index(op.f('ix_aluguel_itens_status_item'), table_name='aluguel_itens')
    op.drop_index(op.f('ix_aluguel_itens_produto_id'), table_name='aluguel_itens')
    op.drop_index(op.f('ix_aluguel_itens_aluguel_id'), table_name='aluguel_itens')
    op.drop_table('aluguel_itens')
    op.drop_index(op.f('ix_produtos_unidade_base_id'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_sku'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_produto_base_id'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_nome_comercial'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_marca_id'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_eh_alugavel'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_ativo'), table_name='produtos')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_compras_usuario_id'), table_name='compras')
    op.drop_index(op.f('ix_compras_status'), table_name='compras')
    op.drop_index(op.f('ix_compras_numero_documento'), table_name='compras')
    op.drop_index(op.f('ix_compras_nfe_documento_id'), table_name='compras')
    op.drop_index(op.f('ix_compras_fornecedor_id'), table_name='compras')
    op.drop_index(op.f('ix_compras_data_compra'), table_name='compras')
    op.drop_table('compras')
    op.drop_index(op.f('ix_alugueis_status'), table_name='alugueis')
    op.drop_index(op.f('ix_alugueis_evento_id'), table_name='alugueis')
    op.drop_index(op.f('ix_alugueis_data_saida_prevista'), table_name='alugueis')
    op.drop_index(op.f('ix_alugueis_data_devolucao_real'), table_name='alugueis')
    op.drop_index(op.f('ix_alugueis_data_devolucao_prevista'), table_name='alugueis')
    op.drop_index(op.f('ix_alugueis_cliente_id'), table_name='alugueis')
    op.drop_table('alugueis')
    op.drop_index(op.f('ix_produtos_base_nome_base'), table_name='produtos_base')
    op.drop_index(op.f('ix_produtos_base_categoria_principal_id'), table_name='produtos_base')
    op.drop_table('produtos_base')
    op.drop_index(op.f('ix_nfe_documentos_xml_hash'), table_name='nfe_documentos')
    op.drop_index(op.f('ix_nfe_documentos_usuario_id'), table_name='nfe_documentos')
    op.drop_index(op.f('ix_nfe_documentos_status_importacao'), table_name='nfe_documentos')
    op.drop_index(op.f('ix_nfe_documentos_serie'), table_name='nfe_documentos')
    op.drop_index(op.f('ix_nfe_documentos_recebida_em'), table_name='nfe_documentos')
    op.drop_index(op.f('ix_nfe_documentos_numero'), table_name='nfe_documentos')
    op.drop_index(op.f('ix_nfe_documentos_fornecedor_id'), table_name='nfe_documentos')
    op.drop_index(op.f('ix_nfe_documentos_data_emissao'), table_name='nfe_documentos')
    op.drop_index(op.f('ix_nfe_documentos_chave_acesso'), table_name='nfe_documentos')
    op.drop_table('nfe_documentos')
    op.drop_index(op.f('ix_eventos_status'), table_name='eventos')
    op.drop_index(op.f('ix_eventos_nome'), table_name='eventos')
    op.drop_index(op.f('ix_eventos_data_inicio'), table_name='eventos')
    op.drop_index(op.f('ix_eventos_data_fim'), table_name='eventos')
    op.drop_index(op.f('ix_eventos_cliente_id'), table_name='eventos')
    op.drop_table('eventos')
    op.drop_index(op.f('ix_usuarios_perfil'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_unidades_sigla'), table_name='unidades')
    op.drop_table('unidades')
    op.drop_index(op.f('ix_marcas_nome'), table_name='marcas')
    op.drop_table('marcas')
    op.drop_index(op.f('ix_locais_tipo'), table_name='locais')
    op.drop_index(op.f('ix_locais_nome'), table_name='locais')
    op.drop_table('locais')
    op.drop_index(op.f('ix_fornecedores_nome'), table_name='fornecedores')
    op.drop_index(op.f('ix_fornecedores_documento'), table_name='fornecedores')
    op.drop_table('fornecedores')
    op.drop_index(op.f('ix_clientes_nome'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_documento'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_categorias_produto_tipo'), table_name='categorias_produto')
    op.drop_index(op.f('ix_categorias_produto_parent_id'), table_name='categorias_produto')
    op.drop_index(op.f('ix_categorias_produto_nome'), table_name='categorias_produto')
    op.drop_table('categorias_produto')
    # ### end Alembic commands ###
