"""add fotos devolução de aluguel

Revision ID: 336dedd129cc
Revises: e5439e13eb99
Create Date: 2026-02-07 05:56:04.555718

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336dedd129cc'
down_revision = 'e5439e13eb99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluguel_devolucao_fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluguel_item_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('movimentacao_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('mime', sa.String(length=120), nullable=True),
    sa.Column('nome_original', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aluguel_item_id'], ['aluguel_itens.id'], ),
    sa.ForeignKeyConstraint(['movimentacao_id'], ['movimentacoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aluguel_devolucao_fotos_aluguel_item_id'), 'aluguel_devolucao_fotos', ['aluguel_item_id'], unique=False)
    op.create_index(op.f('ix_aluguel_devolucao_fotos_movimentacao_id'), 'aluguel_devolucao_fotos', ['movimentacao_id'], unique=False)
    op.create_index(op.f('ix_aluguel_devolucao_fotos_usuario_id'), 'aluguel_devolucao_fotos', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aluguel_devolucao_fotos_usuario_id'), table_name='aluguel_devolucao_fotos')
    op.drop_index(op.f('ix_aluguel_devolucao_fotos_movimentacao_id'), table_name='aluguel_devolucao_fotos')
    op.drop_index(op.f('ix_aluguel_devolucao_fotos_aluguel_item_id'), table_name='aluguel_devolucao_fotos')
    op.drop_table('aluguel_devolucao_fotos')
    # ### end Alembic commands ###
