"""add modelo mao de obra

Revision ID: 78bffc97a3fe
Revises: f8c9ef51980d
Create Date: 2026-02-09 08:27:19.721013

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78bffc97a3fe'
down_revision = 'f8c9ef51980d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
