"""modulo receptor de notas

Revision ID: 7c58fded9b6e
Revises: 80e73ba0cfc0
Create Date: 2026-03-10 15:58:49.534092

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c58fded9b6e'
down_revision = '80e73ba0cfc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificados_fiscais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_nome', sa.String(length=180), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('ambiente', sa.String(length=20), nullable=False),
    sa.Column('tipo_certificado', sa.String(length=20), nullable=False),
    sa.Column('arquivo_path', sa.Text(), nullable=False),
    sa.Column('senha_criptografada', sa.Text(), nullable=False),
    sa.Column('data_validade', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultimo_nsu', sa.String(length=20), nullable=True),
    sa.Column('ultima_sincronizacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sincronizacao_automatica', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificados_fiscais_ambiente'), 'certificados_fiscais', ['ambiente'], unique=False)
    op.create_index(op.f('ix_certificados_fiscais_ativo'), 'certificados_fiscais', ['ativo'], unique=False)
    op.create_index(op.f('ix_certificados_fiscais_cnpj'), 'certificados_fiscais', ['cnpj'], unique=True)
    op.create_index(op.f('ix_certificados_fiscais_empresa_nome'), 'certificados_fiscais', ['empresa_nome'], unique=False)
    op.create_index(op.f('ix_certificados_fiscais_sincronizacao_automatica'), 'certificados_fiscais', ['sincronizacao_automatica'], unique=False)
    op.create_index(op.f('ix_certificados_fiscais_ultimo_nsu'), 'certificados_fiscais', ['ultimo_nsu'], unique=False)
    op.create_table('notas_recebidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificado_fiscal_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('compra_id', sa.Integer(), nullable=True),
    sa.Column('chave_acesso', sa.String(length=44), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('serie', sa.String(length=10), nullable=True),
    sa.Column('modelo', sa.String(length=10), nullable=True),
    sa.Column('fornecedor_nome', sa.String(length=180), nullable=False),
    sa.Column('fornecedor_cnpj', sa.String(length=20), nullable=True),
    sa.Column('natureza_operacao', sa.String(length=255), nullable=True),
    sa.Column('cfop_predominante', sa.String(length=10), nullable=True),
    sa.Column('data_emissao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_autorizacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.Column('valor_produtos', sa.Float(), nullable=True),
    sa.Column('valor_frete', sa.Float(), nullable=True),
    sa.Column('valor_desconto', sa.Float(), nullable=True),
    sa.Column('valor_outros', sa.Float(), nullable=True),
    sa.Column('protocolo', sa.String(length=40), nullable=True),
    sa.Column('nsu', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('xml_path', sa.Text(), nullable=True),
    sa.Column('xml_hash', sa.String(length=128), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('importada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['certificado_fiscal_id'], ['certificados_fiscais.id'], ),
    sa.ForeignKeyConstraint(['compra_id'], ['compras.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave_acesso', name='uq_notas_recebidas_chave_acesso')
    )
    op.create_index(op.f('ix_notas_recebidas_certificado_fiscal_id'), 'notas_recebidas', ['certificado_fiscal_id'], unique=False)
    op.create_index(op.f('ix_notas_recebidas_cfop_predominante'), 'notas_recebidas', ['cfop_predominante'], unique=False)
    op.create_index(op.f('ix_notas_recebidas_chave_acesso'), 'notas_recebidas', ['chave_acesso'], unique=False)
    op.create_index(op.f('ix_notas_recebidas_compra_id'), 'notas_recebidas', ['compra_id'], unique=False)
    op.create_index(op.f('ix_notas_recebidas_data_autorizacao'), 'notas_recebidas', ['data_autorizacao'], unique=False)
    op.create_index(op.f('ix_notas_recebidas_data_emissao'), 'notas_recebidas', ['data_emissao'], unique=False)
    op.create_index(op.f('ix_notas_recebidas_fornecedor_cnpj'), 'notas_recebidas', ['fornecedor_cnpj'], unique=False)
    op.create_index(op.f('ix_notas_recebidas_fornecedor_id'), 'notas_recebidas', ['fornecedor_id'], unique=False)
    op.create_index(op.f('ix_notas_recebidas_fornecedor_nome'), 'notas_recebidas', ['fornecedor_nome'], unique=False)
    op.create_index(op.f('ix_notas_recebidas_modelo'), 'notas_recebidas', ['modelo'], unique=False)
    op.create_index(op.f('ix_notas_recebidas_nsu'), 'notas_recebidas', ['nsu'], unique=False)
    op.create_index(op.f('ix_notas_recebidas_numero'), 'notas_recebidas', ['numero'], unique=False)
    op.create_index(op.f('ix_notas_recebidas_protocolo'), 'notas_recebidas', ['protocolo'], unique=False)
    op.create_index(op.f('ix_notas_recebidas_serie'), 'notas_recebidas', ['serie'], unique=False)
    op.create_index(op.f('ix_notas_recebidas_status'), 'notas_recebidas', ['status'], unique=False)
    op.create_index(op.f('ix_notas_recebidas_xml_hash'), 'notas_recebidas', ['xml_hash'], unique=False)
    op.create_table('fornecedor_produto_vinculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_cnpj', sa.String(length=20), nullable=False),
    sa.Column('codigo_fornecedor', sa.String(length=80), nullable=True),
    sa.Column('descricao_fornecedor', sa.String(length=255), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('embalagem_id', sa.Integer(), nullable=True),
    sa.Column('unidade_informada_id', sa.Integer(), nullable=True),
    sa.Column('fator_para_base', sa.Float(), nullable=True),
    sa.Column('confianca', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['embalagem_id'], ['produto_embalagens.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['unidade_informada_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fornecedor_cnpj', 'codigo_fornecedor', name='uq_fornecedor_produto_vinculo_codigo')
    )
    op.create_index(op.f('ix_fornecedor_produto_vinculos_codigo_fornecedor'), 'fornecedor_produto_vinculos', ['codigo_fornecedor'], unique=False)
    op.create_index(op.f('ix_fornecedor_produto_vinculos_descricao_fornecedor'), 'fornecedor_produto_vinculos', ['descricao_fornecedor'], unique=False)
    op.create_index(op.f('ix_fornecedor_produto_vinculos_embalagem_id'), 'fornecedor_produto_vinculos', ['embalagem_id'], unique=False)
    op.create_index(op.f('ix_fornecedor_produto_vinculos_fornecedor_cnpj'), 'fornecedor_produto_vinculos', ['fornecedor_cnpj'], unique=False)
    op.create_index(op.f('ix_fornecedor_produto_vinculos_produto_id'), 'fornecedor_produto_vinculos', ['produto_id'], unique=False)
    op.create_index(op.f('ix_fornecedor_produto_vinculos_unidade_informada_id'), 'fornecedor_produto_vinculos', ['unidade_informada_id'], unique=False)
    op.create_table('notas_importacao_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota_recebida_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo_evento', sa.String(length=40), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['nota_recebida_id'], ['notas_recebidas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notas_importacao_logs_nota_recebida_id'), 'notas_importacao_logs', ['nota_recebida_id'], unique=False)
    op.create_index(op.f('ix_notas_importacao_logs_tipo_evento'), 'notas_importacao_logs', ['tipo_evento'], unique=False)
    op.create_index(op.f('ix_notas_importacao_logs_usuario_id'), 'notas_importacao_logs', ['usuario_id'], unique=False)
    op.create_table('notas_recebidas_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota_recebida_id', sa.Integer(), nullable=False),
    sa.Column('numero_item', sa.Integer(), nullable=False),
    sa.Column('codigo_fornecedor', sa.String(length=80), nullable=True),
    sa.Column('codigo_barras', sa.String(length=64), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('ncm', sa.String(length=20), nullable=True),
    sa.Column('cfop', sa.String(length=10), nullable=True),
    sa.Column('unidade_comercial', sa.String(length=20), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('embalagem_id', sa.Integer(), nullable=True),
    sa.Column('unidade_informada_id', sa.Integer(), nullable=True),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('status_conciliacao', sa.String(length=30), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['embalagem_id'], ['produto_embalagens.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['nota_recebida_id'], ['notas_recebidas.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['unidade_informada_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nota_recebida_id', 'numero_item', name='uq_notas_recebidas_itens_nota_item')
    )
    op.create_index(op.f('ix_notas_recebidas_itens_cfop'), 'notas_recebidas_itens', ['cfop'], unique=False)
    op.create_index(op.f('ix_notas_recebidas_itens_codigo_barras'), 'notas_recebidas_itens', ['codigo_barras'], unique=False)
    op.create_index(op.f('ix_notas_recebidas_itens_codigo_fornecedor'), 'notas_recebidas_itens', ['codigo_fornecedor'], unique=False)
    op.create_index(op.f('ix_notas_recebidas_itens_descricao'), 'notas_recebidas_itens', ['descricao'], unique=False)
    op.create_index(op.f('ix_notas_recebidas_itens_embalagem_id'), 'notas_recebidas_itens', ['embalagem_id'], unique=False)
    op.create_index(op.f('ix_notas_recebidas_itens_lote_id'), 'notas_recebidas_itens', ['lote_id'], unique=False)
    op.create_index(op.f('ix_notas_recebidas_itens_ncm'), 'notas_recebidas_itens', ['ncm'], unique=False)
    op.create_index(op.f('ix_notas_recebidas_itens_nota_recebida_id'), 'notas_recebidas_itens', ['nota_recebida_id'], unique=False)
    op.create_index(op.f('ix_notas_recebidas_itens_produto_id'), 'notas_recebidas_itens', ['produto_id'], unique=False)
    op.create_index(op.f('ix_notas_recebidas_itens_status_conciliacao'), 'notas_recebidas_itens', ['status_conciliacao'], unique=False)
    op.create_index(op.f('ix_notas_recebidas_itens_unidade_informada_id'), 'notas_recebidas_itens', ['unidade_informada_id'], unique=False)
    op.create_table('notas_conciliacoes_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota_recebida_item_id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=30), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('embalagem_id', sa.Integer(), nullable=True),
    sa.Column('unidade_informada_id', sa.Integer(), nullable=True),
    sa.Column('fator_para_base', sa.Float(), nullable=True),
    sa.Column('barcode_final', sa.String(length=64), nullable=True),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('criar_produto_novo', sa.Boolean(), nullable=False),
    sa.Column('nome_produto_sugerido', sa.String(length=220), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('validado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['embalagem_id'], ['produto_embalagens.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['nota_recebida_item_id'], ['notas_recebidas_itens.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['unidade_informada_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nota_recebida_item_id', name='uq_notas_conciliacoes_itens_item')
    )
    op.create_index(op.f('ix_notas_conciliacoes_itens_acao'), 'notas_conciliacoes_itens', ['acao'], unique=False)
    op.create_index(op.f('ix_notas_conciliacoes_itens_barcode_final'), 'notas_conciliacoes_itens', ['barcode_final'], unique=False)
    op.create_index(op.f('ix_notas_conciliacoes_itens_embalagem_id'), 'notas_conciliacoes_itens', ['embalagem_id'], unique=False)
    op.create_index(op.f('ix_notas_conciliacoes_itens_lote_id'), 'notas_conciliacoes_itens', ['lote_id'], unique=False)
    op.create_index(op.f('ix_notas_conciliacoes_itens_nota_recebida_item_id'), 'notas_conciliacoes_itens', ['nota_recebida_item_id'], unique=False)
    op.create_index(op.f('ix_notas_conciliacoes_itens_produto_id'), 'notas_conciliacoes_itens', ['produto_id'], unique=False)
    op.create_index(op.f('ix_notas_conciliacoes_itens_unidade_informada_id'), 'notas_conciliacoes_itens', ['unidade_informada_id'], unique=False)
    op.create_index(op.f('ix_notas_conciliacoes_itens_validado'), 'notas_conciliacoes_itens', ['validado'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notas_conciliacoes_itens_validado'), table_name='notas_conciliacoes_itens')
    op.drop_index(op.f('ix_notas_conciliacoes_itens_unidade_informada_id'), table_name='notas_conciliacoes_itens')
    op.drop_index(op.f('ix_notas_conciliacoes_itens_produto_id'), table_name='notas_conciliacoes_itens')
    op.drop_index(op.f('ix_notas_conciliacoes_itens_nota_recebida_item_id'), table_name='notas_conciliacoes_itens')
    op.drop_index(op.f('ix_notas_conciliacoes_itens_lote_id'), table_name='notas_conciliacoes_itens')
    op.drop_index(op.f('ix_notas_conciliacoes_itens_embalagem_id'), table_name='notas_conciliacoes_itens')
    op.drop_index(op.f('ix_notas_conciliacoes_itens_barcode_final'), table_name='notas_conciliacoes_itens')
    op.drop_index(op.f('ix_notas_conciliacoes_itens_acao'), table_name='notas_conciliacoes_itens')
    op.drop_table('notas_conciliacoes_itens')
    op.drop_index(op.f('ix_notas_recebidas_itens_unidade_informada_id'), table_name='notas_recebidas_itens')
    op.drop_index(op.f('ix_notas_recebidas_itens_status_conciliacao'), table_name='notas_recebidas_itens')
    op.drop_index(op.f('ix_notas_recebidas_itens_produto_id'), table_name='notas_recebidas_itens')
    op.drop_index(op.f('ix_notas_recebidas_itens_nota_recebida_id'), table_name='notas_recebidas_itens')
    op.drop_index(op.f('ix_notas_recebidas_itens_ncm'), table_name='notas_recebidas_itens')
    op.drop_index(op.f('ix_notas_recebidas_itens_lote_id'), table_name='notas_recebidas_itens')
    op.drop_index(op.f('ix_notas_recebidas_itens_embalagem_id'), table_name='notas_recebidas_itens')
    op.drop_index(op.f('ix_notas_recebidas_itens_descricao'), table_name='notas_recebidas_itens')
    op.drop_index(op.f('ix_notas_recebidas_itens_codigo_fornecedor'), table_name='notas_recebidas_itens')
    op.drop_index(op.f('ix_notas_recebidas_itens_codigo_barras'), table_name='notas_recebidas_itens')
    op.drop_index(op.f('ix_notas_recebidas_itens_cfop'), table_name='notas_recebidas_itens')
    op.drop_table('notas_recebidas_itens')
    op.drop_index(op.f('ix_notas_importacao_logs_usuario_id'), table_name='notas_importacao_logs')
    op.drop_index(op.f('ix_notas_importacao_logs_tipo_evento'), table_name='notas_importacao_logs')
    op.drop_index(op.f('ix_notas_importacao_logs_nota_recebida_id'), table_name='notas_importacao_logs')
    op.drop_table('notas_importacao_logs')
    op.drop_index(op.f('ix_fornecedor_produto_vinculos_unidade_informada_id'), table_name='fornecedor_produto_vinculos')
    op.drop_index(op.f('ix_fornecedor_produto_vinculos_produto_id'), table_name='fornecedor_produto_vinculos')
    op.drop_index(op.f('ix_fornecedor_produto_vinculos_fornecedor_cnpj'), table_name='fornecedor_produto_vinculos')
    op.drop_index(op.f('ix_fornecedor_produto_vinculos_embalagem_id'), table_name='fornecedor_produto_vinculos')
    op.drop_index(op.f('ix_fornecedor_produto_vinculos_descricao_fornecedor'), table_name='fornecedor_produto_vinculos')
    op.drop_index(op.f('ix_fornecedor_produto_vinculos_codigo_fornecedor'), table_name='fornecedor_produto_vinculos')
    op.drop_table('fornecedor_produto_vinculos')
    op.drop_index(op.f('ix_notas_recebidas_xml_hash'), table_name='notas_recebidas')
    op.drop_index(op.f('ix_notas_recebidas_status'), table_name='notas_recebidas')
    op.drop_index(op.f('ix_notas_recebidas_serie'), table_name='notas_recebidas')
    op.drop_index(op.f('ix_notas_recebidas_protocolo'), table_name='notas_recebidas')
    op.drop_index(op.f('ix_notas_recebidas_numero'), table_name='notas_recebidas')
    op.drop_index(op.f('ix_notas_recebidas_nsu'), table_name='notas_recebidas')
    op.drop_index(op.f('ix_notas_recebidas_modelo'), table_name='notas_recebidas')
    op.drop_index(op.f('ix_notas_recebidas_fornecedor_nome'), table_name='notas_recebidas')
    op.drop_index(op.f('ix_notas_recebidas_fornecedor_id'), table_name='notas_recebidas')
    op.drop_index(op.f('ix_notas_recebidas_fornecedor_cnpj'), table_name='notas_recebidas')
    op.drop_index(op.f('ix_notas_recebidas_data_emissao'), table_name='notas_recebidas')
    op.drop_index(op.f('ix_notas_recebidas_data_autorizacao'), table_name='notas_recebidas')
    op.drop_index(op.f('ix_notas_recebidas_compra_id'), table_name='notas_recebidas')
    op.drop_index(op.f('ix_notas_recebidas_chave_acesso'), table_name='notas_recebidas')
    op.drop_index(op.f('ix_notas_recebidas_cfop_predominante'), table_name='notas_recebidas')
    op.drop_index(op.f('ix_notas_recebidas_certificado_fiscal_id'), table_name='notas_recebidas')
    op.drop_table('notas_recebidas')
    op.drop_index(op.f('ix_certificados_fiscais_ultimo_nsu'), table_name='certificados_fiscais')
    op.drop_index(op.f('ix_certificados_fiscais_sincronizacao_automatica'), table_name='certificados_fiscais')
    op.drop_index(op.f('ix_certificados_fiscais_empresa_nome'), table_name='certificados_fiscais')
    op.drop_index(op.f('ix_certificados_fiscais_cnpj'), table_name='certificados_fiscais')
    op.drop_index(op.f('ix_certificados_fiscais_ativo'), table_name='certificados_fiscais')
    op.drop_index(op.f('ix_certificados_fiscais_ambiente'), table_name='certificados_fiscais')
    op.drop_table('certificados_fiscais')
    # ### end Alembic commands ###
