"""add modelo mao de obra

Revision ID: 7caefaac6e7d
Revises: e84c710cc3fd
Create Date: 2026-02-09 08:52:18.207569

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7caefaac6e7d'
down_revision = 'e84c710cc3fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mao_de_obra_modelos_user_id', table_name='mao_de_obra_modelos')
    op.drop_constraint('uq_mdo_modelo_user_nome', 'mao_de_obra_modelos', type_='unique')
    op.create_unique_constraint('uq_mdo_modelo_nome', 'mao_de_obra_modelos', ['nome'])
    op.drop_constraint('mao_de_obra_modelos_user_id_fkey', 'mao_de_obra_modelos', type_='foreignkey')
    op.drop_column('mao_de_obra_modelos', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mao_de_obra_modelos', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('mao_de_obra_modelos_user_id_fkey', 'mao_de_obra_modelos', 'usuarios', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_mdo_modelo_nome', 'mao_de_obra_modelos', type_='unique')
    op.create_unique_constraint('uq_mdo_modelo_user_nome', 'mao_de_obra_modelos', ['user_id', 'nome'])
    op.create_index('ix_mao_de_obra_modelos_user_id', 'mao_de_obra_modelos', ['user_id'], unique=False)
    # ### end Alembic commands ###
