"""create setores_consumo table

Revision ID: 80e73ba0cfc0
Revises: 7caefaac6e7d
Create Date: 2026-03-10 03:13:46.816994

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e73ba0cfc0'
down_revision = '7caefaac6e7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setores_consumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setores_consumo_id'), 'setores_consumo', ['id'], unique=False)
    op.create_index(op.f('ix_setores_consumo_nome'), 'setores_consumo', ['nome'], unique=True)
    op.add_column('movimentacoes', sa.Column('setor_consumo_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_movimentacoes_setor_consumo_id'), 'movimentacoes', ['setor_consumo_id'], unique=False)
    op.create_foreign_key(None, 'movimentacoes', 'setores_consumo', ['setor_consumo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movimentacoes', type_='foreignkey')
    op.drop_index(op.f('ix_movimentacoes_setor_consumo_id'), table_name='movimentacoes')
    op.drop_column('movimentacoes', 'setor_consumo_id')
    op.drop_index(op.f('ix_setores_consumo_nome'), table_name='setores_consumo')
    op.drop_index(op.f('ix_setores_consumo_id'), table_name='setores_consumo')
    op.drop_table('setores_consumo')
    # ### end Alembic commands ###
