"""add mao de obra

Revision ID: bbf6b3b4bdfa
Revises: 336dedd129cc
Create Date: 2026-02-07 07:44:56.722847

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbf6b3b4bdfa'
down_revision = '336dedd129cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventos', sa.Column('receita', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('eventos', sa.Column('receita_convite_extra', sa.Numeric(precision=14, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eventos', 'receita_convite_extra')
    op.drop_column('eventos', 'receita')
    # ### end Alembic commands ###
