"""add mao de obra att

Revision ID: bf32269f8c98
Revises: bbf6b3b4bdfa
Create Date: 2026-02-07 08:03:51.290860

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf32269f8c98'
down_revision = 'bbf6b3b4bdfa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mao_de_obra_grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('nome_grupo', sa.String(length=160), nullable=False),
    sa.Column('tipo_evento', sa.String(length=80), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mao_de_obra_grupos_evento_id'), 'mao_de_obra_grupos', ['evento_id'], unique=False)
    op.create_index(op.f('ix_mao_de_obra_grupos_nome_grupo'), 'mao_de_obra_grupos', ['nome_grupo'], unique=False)
    op.create_index(op.f('ix_mao_de_obra_grupos_tipo_evento'), 'mao_de_obra_grupos', ['tipo_evento'], unique=False)
    op.create_table('mao_de_obra_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=120), nullable=True),
    sa.Column('nome', sa.String(length=180), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['mao_de_obra_grupos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mao_de_obra_itens_categoria'), 'mao_de_obra_itens', ['categoria'], unique=False)
    op.create_index(op.f('ix_mao_de_obra_itens_grupo_id'), 'mao_de_obra_itens', ['grupo_id'], unique=False)
    op.create_index(op.f('ix_mao_de_obra_itens_nome'), 'mao_de_obra_itens', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mao_de_obra_itens_nome'), table_name='mao_de_obra_itens')
    op.drop_index(op.f('ix_mao_de_obra_itens_grupo_id'), table_name='mao_de_obra_itens')
    op.drop_index(op.f('ix_mao_de_obra_itens_categoria'), table_name='mao_de_obra_itens')
    op.drop_table('mao_de_obra_itens')
    op.drop_index(op.f('ix_mao_de_obra_grupos_tipo_evento'), table_name='mao_de_obra_grupos')
    op.drop_index(op.f('ix_mao_de_obra_grupos_nome_grupo'), table_name='mao_de_obra_grupos')
    op.drop_index(op.f('ix_mao_de_obra_grupos_evento_id'), table_name='mao_de_obra_grupos')
    op.drop_table('mao_de_obra_grupos')
    # ### end Alembic commands ###
