"""add novo_model

Revision ID: dbce539e8150
Revises: 32371a412bd4
Create Date: 2026-02-03 20:46:40.591098

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbce539e8150'
down_revision = '32371a412bd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('despesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=40), nullable=True),
    sa.Column('fornecedor_nome', sa.String(length=180), nullable=True),
    sa.Column('documento_ref', sa.String(length=80), nullable=True),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_despesas_categoria'), 'despesas', ['categoria'], unique=False)
    op.create_index(op.f('ix_despesas_data'), 'despesas', ['data'], unique=False)
    op.create_index(op.f('ix_despesas_evento_id'), 'despesas', ['evento_id'], unique=False)
    op.create_index(op.f('ix_despesas_id'), 'despesas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_despesas_id'), table_name='despesas')
    op.drop_index(op.f('ix_despesas_evento_id'), table_name='despesas')
    op.drop_index(op.f('ix_despesas_data'), table_name='despesas')
    op.drop_index(op.f('ix_despesas_categoria'), table_name='despesas')
    op.drop_table('despesas')
    # ### end Alembic commands ###
