"""add orcamentos

Revision ID: deebbce9eae1
Revises: 073776a91a8f
Create Date: 2026-02-05 03:23:26.593361

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deebbce9eae1'
down_revision = '073776a91a8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
