"""add orcamentos

Revision ID: e5439e13eb99
Revises: eb9c8b6446e2
Create Date: 2026-02-05 03:31:18.674145

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5439e13eb99'
down_revision = 'eb9c8b6446e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orcamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.Column('data_saida_prevista', sa.Date(), nullable=True),
    sa.Column('data_devolucao_prevista', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orcamentos_cliente_id'), 'orcamentos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_orcamentos_evento_id'), 'orcamentos', ['evento_id'], unique=False)
    op.create_index(op.f('ix_orcamentos_status'), 'orcamentos', ['status'], unique=False)
    op.create_table('orcamento_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_base', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orcamento_itens_orcamento_id'), 'orcamento_itens', ['orcamento_id'], unique=False)
    op.create_index(op.f('ix_orcamento_itens_produto_id'), 'orcamento_itens', ['produto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orcamento_itens_produto_id'), table_name='orcamento_itens')
    op.drop_index(op.f('ix_orcamento_itens_orcamento_id'), table_name='orcamento_itens')
    op.drop_table('orcamento_itens')
    op.drop_index(op.f('ix_orcamentos_status'), table_name='orcamentos')
    op.drop_index(op.f('ix_orcamentos_evento_id'), table_name='orcamentos')
    op.drop_index(op.f('ix_orcamentos_cliente_id'), table_name='orcamentos')
    op.drop_table('orcamentos')
    # ### end Alembic commands ###
