"""add modelo mao de obra

Revision ID: e84c710cc3fd
Revises: 78bffc97a3fe
Create Date: 2026-02-09 08:28:54.081326

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e84c710cc3fd'
down_revision = '78bffc97a3fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mao_de_obra_modelos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('tipo_evento', sa.String(length=80), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'nome', name='uq_mdo_modelo_user_nome')
    )
    op.create_index(op.f('ix_mao_de_obra_modelos_nome'), 'mao_de_obra_modelos', ['nome'], unique=False)
    op.create_index(op.f('ix_mao_de_obra_modelos_tipo_evento'), 'mao_de_obra_modelos', ['tipo_evento'], unique=False)
    op.create_index(op.f('ix_mao_de_obra_modelos_user_id'), 'mao_de_obra_modelos', ['user_id'], unique=False)
    op.create_table('mao_de_obra_modelo_grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('nome_grupo', sa.String(length=160), nullable=False),
    sa.Column('tipo_evento', sa.String(length=80), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['modelo_id'], ['mao_de_obra_modelos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mao_de_obra_modelo_grupos_modelo_id'), 'mao_de_obra_modelo_grupos', ['modelo_id'], unique=False)
    op.create_index(op.f('ix_mao_de_obra_modelo_grupos_nome_grupo'), 'mao_de_obra_modelo_grupos', ['nome_grupo'], unique=False)
    op.create_index(op.f('ix_mao_de_obra_modelo_grupos_tipo_evento'), 'mao_de_obra_modelo_grupos', ['tipo_evento'], unique=False)
    op.create_table('mao_de_obra_modelo_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=120), nullable=True),
    sa.Column('nome', sa.String(length=180), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['mao_de_obra_modelo_grupos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mao_de_obra_modelo_itens_categoria'), 'mao_de_obra_modelo_itens', ['categoria'], unique=False)
    op.create_index(op.f('ix_mao_de_obra_modelo_itens_grupo_id'), 'mao_de_obra_modelo_itens', ['grupo_id'], unique=False)
    op.create_index(op.f('ix_mao_de_obra_modelo_itens_nome'), 'mao_de_obra_modelo_itens', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mao_de_obra_modelo_itens_nome'), table_name='mao_de_obra_modelo_itens')
    op.drop_index(op.f('ix_mao_de_obra_modelo_itens_grupo_id'), table_name='mao_de_obra_modelo_itens')
    op.drop_index(op.f('ix_mao_de_obra_modelo_itens_categoria'), table_name='mao_de_obra_modelo_itens')
    op.drop_table('mao_de_obra_modelo_itens')
    op.drop_index(op.f('ix_mao_de_obra_modelo_grupos_tipo_evento'), table_name='mao_de_obra_modelo_grupos')
    op.drop_index(op.f('ix_mao_de_obra_modelo_grupos_nome_grupo'), table_name='mao_de_obra_modelo_grupos')
    op.drop_index(op.f('ix_mao_de_obra_modelo_grupos_modelo_id'), table_name='mao_de_obra_modelo_grupos')
    op.drop_table('mao_de_obra_modelo_grupos')
    op.drop_index(op.f('ix_mao_de_obra_modelos_user_id'), table_name='mao_de_obra_modelos')
    op.drop_index(op.f('ix_mao_de_obra_modelos_tipo_evento'), table_name='mao_de_obra_modelos')
    op.drop_index(op.f('ix_mao_de_obra_modelos_nome'), table_name='mao_de_obra_modelos')
    op.drop_table('mao_de_obra_modelos')
    # ### end Alembic commands ###
