"""add orcamentos

Revision ID: eb9c8b6446e2
Revises: deebbce9eae1
Create Date: 2026-02-05 03:27:02.047466

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb9c8b6446e2'
down_revision = 'deebbce9eae1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
