"""add modelo mao de obra

Revision ID: f8c9ef51980d
Revises: bf32269f8c98
Create Date: 2026-02-09 08:26:50.150040

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8c9ef51980d'
down_revision = 'bf32269f8c98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
